name: Playwright Tests with HTML Report

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests with server
      run: npx start-server-and-test "node server.js" http://localhost:3000 "npx playwright test"

    - name: Copy Playwright report to public/reports/${GITHUB_RUN_ID}
      run: |
        mkdir -p public/reports/${GITHUB_RUN_ID}
        cp -r playwright-report/* public/reports/${GITHUB_RUN_ID}/

    - name: Generate Playwright reports index.html
      run: |
        node public/reports/generate-index.js

    - name: Upload Playwright HTML reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-reports
        path: public/reports/
        retention-days: 7
        
    - name: Display test summary
      if: always()
      run: |
        echo "============================================"
        echo "🎭 Playwright Test Results Summary"
        echo "============================================"
        if [ -f "test-results.json" ]; then
          echo "📊 Results uploaded as artifact: playwright-report"
          echo "💾 Download the HTML report from the Actions tab"
        else
          echo "⚠️  No test results found"
        fi
        echo "============================================"